<?php
/**
 * Created by PhpStorm.
 * User: zvinger
 * Date: 09.05.18
 * Time: 13:38
 */

namespace Obvu\Modules\Api\AdminSubmodules\Content\models\page\object;


use yii\db\ActiveQuery;

/**
 * Class PageQuery
 * @package app\components\database\repository\content\page\models\object
 * @see PageObject
 */
class PageQuery extends ActiveQuery
{
    /**
     * @param null $db
     * @return array|null|PageObject
     */
    public function one($db = NULL)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|PageObject[]
     */
    public function all($db = NULL)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }


}