<?php
/**
 * Created by PhpStorm.
 * User: nik
 * Date: 23.04.19
 * Time: 9:23
 */

namespace Obvu\Modules\Api\Admin\submodules\userControl;


use yii\base\Application;
use yii\base\BootstrapInterface;
use yii\base\Module;
use Zvinger\BaseClasses\app\graphql\base\BaseGraphQLObjectType;

class UserControlModule extends Module implements BootstrapInterface
{
    private static $GQLTypeStore = [];
    public $initFunction;

    /**
     * Bootstrap method to be called during application bootstrap stage.
     * @param Application $app the application currently running
     */

    public function init()
    {
        if (is_callable($this->initFunction)) {
            ($this->initFunction)($this);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function bootstrap($app)
    {
        // TODO: Implement bootstrap() method.
    }

    public static function getGraphQLObjectType($key)
    {
        if (isset(self::$GQLTypeStore[$key])) {
            self::$GQLTypeStore[$key]['type']::initType();
            return self::$GQLTypeStore[$key];
        } else {
            return  null;
        }
    }

    public static function addType($key, $class, $root)
    {
        if (($type = new $class) instanceof BaseGraphQLObjectType){
            self::$GQLTypeStore[$key] = [
                'type' => $type,
                'resolve' => function () use ($root) {
                    return $root;
                }
            ];
        }
    }
}
