<?php


namespace Obvu\Modules\Api\Admin\submodules\siteInfo;


use Obvu\Modules\Api\Admin\submodules\siteInfo\components\getter\BaseSiteInfoDataGetter;
use yii\base\Module;

class SiteInfoModule extends Module
{
    /**
     * @var BaseSiteInfoDataGetter
     */
    public $dataGetter;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function getDataGetter()
    {
        if (!($this->dataGetter instanceof BaseSiteInfoDataGetter)) {
            $this->dataGetter = \Yii::createObject($this->dataGetter);
        }

        return $this->dataGetter;
    }
}