<?php
/**
 * Created by PhpStorm.
 * User: zvinger
 * Date: 09.05.18
 * Time: 13:40
 */

namespace Obvu\Modules\Api\AdminSubmodules\Content\models\widget\object;


use yii\db\ActiveQuery;

/**
 * Class WidgetQuery
 * @package app\components\database\repository\content\widget\models\object
 * @see WidgetObject
 */
class WidgetQuery extends ActiveQuery
{
    public function byKey($key)
    {
        return $this->andWhere(['key' => $key]);
    }

    /**
     * @param null $db
     * @return array|null|WidgetObject
     */
    public function one($db = NULL)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|WidgetObject[]
     */
    public function all($db = NULL)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }


}