<?php
/**
 * Created by PhpStorm.
 * User: zvinger
 * Date: 19.04.18
 * Time: 13:27
 */

namespace Obvu\Modules\Api\Admin\AdminSubmodules\Content;


use app\components\database\repository\post\PostRepository;
use Obvu\Modules\Api\Admin\ApiAdminDwyModule;
use Obvu\Modules\Api\Admin\AdminSubmodules\Content\components\textBlock\AdminTextBlockRepository;
use Obvu\Modules\Api\Admin\AdminSubmodules\Content\interfaces\blog\post\PostAdminRepositoryInterface;

/**
 * Class ApiAdminDwyContentModule
 * @package Obvu\Modules\Api\Admin\AdminSubmodules\Content
 *
 * @property AdminTextBlockRepository textBlock
 */
class ApiAdminDwyContentModule extends ApiAdminDwyModule
{
    public function init()
    {
        $this->components = [
            'textBlock' => AdminTextBlockRepository::class,
        ];
        \Yii::$container->setSingletons([
            PostAdminRepositoryInterface::class => PostRepository::class,
        ]);

        parent::init(); // TODO: Change the autogenerated stub
    }

}