<?php
/**
 * Created by PhpStorm.
 * User: zvinger
 * Date: 19.04.18
 * Time: 13:27
 */

namespace Obvu\Modules\Api\AdminSubmodules\Content;

use Obvu\Modules\Api\AdminSubmodules\Content\components\textBlock\AdminTextBlockRepository;
use Obvu\Modules\Api\Admin\AdminModule;

/**
 * Class ContentModule
 * @package Obvu\Modules\Api\AdminSubmodules\Content
 *
 * @property AdminTextBlockRepository textBlock
 */
class ContentModule extends AdminModule
{
    public function bootstrap($app)
    {
        $app->urlManager->addRules([
            ['class' => 'yii\rest\UrlRule', 'controller' => $this->uniqueId . '/text-block'],
            ['class' => 'yii\rest\UrlRule', 'controller' => $this->uniqueId . '/blog/post'],
            ['class' => 'yii\rest\UrlRule', 'controller' => $this->uniqueId . '/blog/post-category'],
            ['class' => 'yii\rest\UrlRule', 'controller' => $this->uniqueId . '/page'],
            ['class' => 'yii\rest\UrlRule', 'controller' => $this->uniqueId . '/widget'],
        ]);
    }

    public function init()
    {
        $this->components = [
            'textBlock' => AdminTextBlockRepository::class,
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }

}
