<?php


namespace Obvu\Modules\Api\Admin\submodules\crud\components\database\models\crud\element;


use yii\db\ActiveQuery;

/**
 * Class FullCrudElementQuery
 * @package Obvu\Modules\Api\Admin\submodules\crud\components\database\models\crud\element
 * @see FullCrudElementObject
 */
class FullCrudElementQuery extends ActiveQuery
{
    public function byType($type)
    {
        return $this->andWhere(['type' => $type]);
    }

    public function byModule($module)
    {
        return $this->andWhere(['module' => $module]);
    }

    /**
     * @param null $db
     * @return FullCrudElementObject[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return FullCrudElementObject
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }
}
