<?php
/**
 * Created by PhpStorm.
 * User: zvinger
 * Date: 05.05.18
 * Time: 14:10
 */

namespace Obvu\Modules\Api\AdminSubmodules\Content\models\post\object;


use yii\db\ActiveQuery;

/**
 * Class PostQuery
 * @package app\components\database\repository\post\models\object
 * @see PostObject
 */
class PostQuery extends ActiveQuery
{
    /**
     * @param null $db
     * @return array|PostObject[]
     */
    public function all($db = NULL)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|null|PostObject
     */
    public function one($db = NULL)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }


}