<?php
/**
 * Created by PhpStorm.
 * User: zvinger
 * Date: 07.05.18
 * Time: 17:29
 */

namespace Obvu\Modules\Api\AdminSubmodules\Content\models\textBlock\object;


use yii\db\ActiveQuery;

/**
 * Class TextBlockQuery
 * @package Obvu\Modules\Api\AdminSubmodules\Content\models\textBlock\object
 * @see TextBlock
 */
class TextBlockQuery extends ActiveQuery
{
    /**
     * @param null $db
     * @return array|null|TextBlock
     */
    public function one($db = NULL)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return array|TextBlock[]
     */
    public function all($db = NULL)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }


}